ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Controllers/TestProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopOnline_ASM_NET104_CONGNCPH14366.Models;

namespace ShopOnline_ASM_NET104_CONGNCPH14366.Controllers
{
    public class TestProductsController : Controller
    {
        private readonly ShopOnlineContext _context;

        public TestProductsController(ShopOnlineContext context)
        {
            _context = context;
        }

        // GET: TestProducts
        public async Task<IActionResult> Index()
        {
            var shopOnlineContext = _context.Products.Include(p => p.Cat);
            return View(await shopOnlineContext.ToListAsync());
        }

        // GET: TestProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: TestProducts/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId");
            return View();
        }

        // POST: TestProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Descriptions,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitslnStock")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", product.CatId);
            return View(product);
        }

        // GET: TestProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", product.CatId);
            return View(product);
        }

        // POST: TestProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Descriptions,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitslnStock")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatId", product.CatId);
            return View(product);
        }

        // GET: TestProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: TestProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Views/TestProducts/Create.cshtml
@model ShopOnline_ASM_NET104_CONGNCPH14366.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <input asp-for="ProductId" class="form-control" />
                <span asp-validation-for="ProductId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDesc" class="control-label"></label>
                <input asp-for="ShortDesc" class="form-control" />
                <span asp-validation-for="ShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriptions" class="control-label"></label>
                <input asp-for="Descriptions" class="form-control" />
                <span asp-validation-for="Descriptions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class ="form-control" asp-items="ViewBag.CatId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateModified" class="control-label"></label>
                <input asp-for="DateModified" class="form-control" />
                <span asp-validation-for="DateModified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestSellers" class="control-label"></label>
                <input asp-for="BestSellers" class="form-control" />
                <span asp-validation-for="BestSellers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeFlag" class="control-label"></label>
                <input asp-for="HomeFlag" class="form-control" />
                <span asp-validation-for="HomeFlag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitslnStock" class="control-label"></label>
                <input asp-for="UnitslnStock" class="form-control" />
                <span asp-validation-for="UnitslnStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Views/TestProducts/Delete.cshtml
@model ShopOnline_ASM_NET104_CONGNCPH14366.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descriptions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSellers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSellers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitslnStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitslnStock)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cat.CatId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Views/TestProducts/Details.cshtml
@model ShopOnline_ASM_NET104_CONGNCPH14366.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-4 mt-5 mb-5">
    <div class="card" style="width: 18rem;">
        <img src="~/images/products/@Html.DisplayFor(model => model.Thumb)" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title"> @Html.DisplayFor(model => model.ProductName)</h5>
            <p class="card-text">Giá Bán : @Html.DisplayFor(model => model.Price)</p>
            <label class="font-weight-semibold" for="productName">Số Lượng</label>
            <input type="number" class="form-control" id="SL" name="SL" for="SL" />
        </div>
    </div>
</div>

ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Views/TestProducts/Edit.cshtml
@model ShopOnline_ASM_NET104_CONGNCPH14366.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDesc" class="control-label"></label>
                <input asp-for="ShortDesc" class="form-control" />
                <span asp-validation-for="ShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriptions" class="control-label"></label>
                <input asp-for="Descriptions" class="form-control" />
                <span asp-validation-for="Descriptions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class="form-control" asp-items="ViewBag.CatId"></select>
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateModified" class="control-label"></label>
                <input asp-for="DateModified" class="form-control" />
                <span asp-validation-for="DateModified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestSellers" class="control-label"></label>
                <input asp-for="BestSellers" class="form-control" />
                <span asp-validation-for="BestSellers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomeFlag" class="control-label"></label>
                <input asp-for="HomeFlag" class="form-control" />
                <span asp-validation-for="HomeFlag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Active" class="control-label"></label>
                <input asp-for="Active" class="form-control" />
                <span asp-validation-for="Active" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitslnStock" class="control-label"></label>
                <input asp-for="UnitslnStock" class="form-control" />
                <span asp-validation-for="UnitslnStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ShopOnline_ASM_NET104_CONGNCPH14366/ShopOnline_ASM_NET104_CONGNCPH14366/Views/TestProducts/Index.cshtml
@model IEnumerable<ShopOnline_ASM_NET104_CONGNCPH14366.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-4 mt-5 mb-5">
                <div class="card" style="width: 18rem;">
                    <img src="~/images/products/@Html.DisplayFor(modelItem => item.Thumb)" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"> @Html.DisplayFor(modelItem => item.ProductName)</h5>
                        <p class="card-text">Giá Bán : @Html.DisplayFor(modelItem => item.Price)</p>
                        <a asp-controller="TestProducts" asp-action="Details" asp-route-id="@item.ProductId" class="btn btn-primary">Mua Hàng</a>
                    </div>
                </div>
            </div>


        }
    </div>
</div>